In [58]:
from tdc.single_pred import Tox, ADME

data= Tox(name= "AMES")
split= data.get_split(method = 'scaffold')
train_df = split['train']
val_df = split['valid']
test_df = split['test']

Found local copy...
Loading...
Done!
100%|██████████| 7278/7278 [00:01<00:00, 6963.07it/s]

In [59]:
split

{'train':         Drug_ID                                               Drug  Y
 0     Drug 6145                          Nc1cccc([N+](=O)[O-])c1CO  0
 1     Drug 6146                O=[N+]([O-])c1cccc(O)c1[N+](=O)[O-]  1
 2     Drug 4100                                     Cc1cc(Cl)ccc1O  0
 3     Drug 2053                             CNC(=O)Oc1ccccc1OC(C)C  1
 4     Drug 6151             Cc1cc([N+](=O)[O-])cc([N+](=O)[O-])c1C  0
 ...         ...                                                ... ..
 5089    Drug 71                Cc1cccc(Nc2cc(Cl)nc(SCC(=O)O)n2)c1C  0
 5090  Drug 2746  CN1CCN(c2cc3c(cc2F)n2c(=O)n(O)c(=O)cc2n3C2CC2)CC1  1
 5091  Drug 2652  CN1CCN(c2cc3c(cc2F)n2c(=O)[nH]c(=O)cc2n3C2CC2)CC1  1
 5092  Drug 1691                      CC1(c2ccccc2)C(=O)c2ccccc2N1O  0
 5093  Drug 4974    C=C1C(=O)C23CCC4C(C)(C(=O)O)CCCC4(C)C2CCC1(O)C3  1

 [5094 rows x 3 columns],
 'valid':        Drug_ID                                               Drug  Y
 0    Drug 2736  O=[N+]([O-])c1ccc(-c2nc3n(c2[N+](=O)[O-])CCS3)cc1  1
 1    Drug 4607            O=[N+]([O-])c1c(-c2ccc(Cl)cc2)nc2n1CCS2  1
 2    Drug 4511             Cc1ccc(-c2nc3n(c2[N+](=O)[O-])CCS3)cc1  1
 3    Drug 2439            COC(=O)[C@]12O[C@@]1(C)[C@@](C)(O)NC2=O  1
 4    Drug 3245            CC[C@@]12O[C@]1(C(=O)OC)C(=O)N[C@]2(C)O  1
 ..         ...                                                ... ..
 722  Drug 6846          O=c1c2c(O)cccc2oc2c3c(cc(O)c12)OC1OC=CC31  1
 723    Drug 82  COc1ccc(O)c2c(=O)c3c(OC)cc4c(c3oc12)[C@@H]1C=C...  1
 724  Drug 6421         COc1cc2c(c3oc4cccc(O)c4c(=O)c13)C1C=COC1O2  1
 725  Drug 6946     COc1ccc(O)c2c(=O)c3c(OC)cc4c(c3oc12)C1C=COC1O4  1
 726  Drug 6726   COC(=O)c1cccc2oc3c4c(cc(OC)c3c(=O)c12)OC1OC=CC41  1

 [727 rows x 3 columns],
 'test':         Drug_ID                                               Drug  Y
 0     Drug 2641            CC(=O)Nc1ccc2c(=O)c(=O)c3cccc4ccc1c2c43  1
 1     Drug 2892       O=c1c(=O)c2c([N+](=O)[O-])ccc3ccc4cccc1c4c32  1
 2     Drug 4833       O=c1c(=O)c2ccc([N+](=O)[O-])c3ccc4cccc1c4c32  1
 3     Drug 1191                     O=c1c(=O)c2cccc3ccc4cccc1c4c32  0
 4     Drug 6777           COC(=O)C12CC1(C=O)C(C=O)C=C1CC(C)(C)CC12  1
 ...         ...                                                ... ..
 1452  Drug 6688         CCc1cc(O)cc2c3c([nH]c12)C(CC)(CC(=O)O)OCC3  1
 1453  Drug 5176            CCc1cccc2c3c([nH]c12)C(CC)(CC(=O)O)OCC3  0
 1454  Drug 4346           CCC1(CC(=O)O)OCCc2c1[nH]c1c(C(C)O)cccc21  0
 1455  Drug 6945  COc1cccc2c(O)c3c(O)c4c(c(O)c3c(O)c12)C(=O)CC(O...  1
 1456    Drug 87          Cc1cc(C)n(-c2[nH]nc(NN)c3c4ccccc4nc2-3)n1  0

 [1457 rows x 3 columns]}

In [60]:
train_df

        Drug_ID                                               Drug  Y
0     Drug 6145                          Nc1cccc([N+](=O)[O-])c1CO  0
1     Drug 6146                O=[N+]([O-])c1cccc(O)c1[N+](=O)[O-]  1
2     Drug 4100                                     Cc1cc(Cl)ccc1O  0
3     Drug 2053                             CNC(=O)Oc1ccccc1OC(C)C  1
4     Drug 6151             Cc1cc([N+](=O)[O-])cc([N+](=O)[O-])c1C  0
...         ...                                                ... ..
5089    Drug 71                Cc1cccc(Nc2cc(Cl)nc(SCC(=O)O)n2)c1C  0
5090  Drug 2746  CN1CCN(c2cc3c(cc2F)n2c(=O)n(O)c(=O)cc2n3C2CC2)CC1  1
5091  Drug 2652  CN1CCN(c2cc3c(cc2F)n2c(=O)[nH]c(=O)cc2n3C2CC2)CC1  1
5092  Drug 1691                      CC1(c2ccccc2)C(=O)c2ccccc2N1O  0
5093  Drug 4974    C=C1C(=O)C23CCC4C(C)(C(=O)O)CCCC4(C)C2CCC1(O)C3  1

[5094 rows x 3 columns]

In [61]:
def row_to_text( row, split='train', dataset='AMES'):
    if dataset == 'AMES':
        text = f"Q: This is the SMILES string of the drug: {row['Drug']}. Is this drug mutagenic?\nA: "
    elif dataset == 'Skin Reaction':
        text = f"Q: This is the SMILES string of the drug: {row['Drug']}. Can this drug cause skin reaction?\nA: "
    if split == 'train':
        text += f"{'Yes' if row['Y']==1 else 'No'}"
    return text

train_df["text"] = train_df.apply(row_to_text, axis=1, split = 'train', dataset = 'AMES')
val_df["text"] = val_df.apply(row_to_text, axis=1, split = 'val', dataset = 'AMES')
test_df["text"] = test_df.apply(row_to_text, axis=1, split = 'test', dataset = 'AMES')

In [62]:
print(test_df['text'][0])

Q: This is the SMILES string of the drug: CC(=O)Nc1ccc2c(=O)c(=O)c3cccc4ccc1c2c43. Is this drug mutagenic?
A:

In [63]:
import os
# Save the train and test dataframes to csv
train_df = train_df[["text"]]
val_df = val_df[["text", "Y"]]
test_df = test_df[["text", "Y"]]
# create AMES directory if it doesn't exist
os.makedirs('./../data/TDC/Skin', exist_ok=True)
train_df.to_csv('./../data/TDC/Skin/train_df.csv', index=False)
val_df.to_csv('./../data/TDC/AMES/val_df.csv', index=False)
test_df.to_csv('./../data/TDC/AMES/test_df.csv', index=False)

In [64]:
from tdc.single_pred import Tox
data = Tox(name = 'Skin Reaction')
split = data.get_split()
train_df = split['train']
val_df = split['valid']
test_df = split['test']

Found local copy...
Loading...
Done!

In [65]:
train_df

,Drug_ID,Drug,Y
0,(2-Bromo-5-propoxyphenyl)-(2-hydroxy-4-methoxy...,CCCOc1ccc(Br)c(C(=O)c2ccc(OC)cc2O)c1,0
1,(2E)-2-Methyl-2-butenal,CC=C(C)C=O,0
2,(2-oxo-1-phenylpyrrolidin-3-yl)-Triphenylphosp...,O=C1C([PH](c2ccccc2)(c2ccccc2)c2ccccc2)CCN1c1c...,0
3,(4Z)-2-Methyl-6-methylene-4-octene,C=C(C=CCC(C)C)CC,0
4,"[4-(Ethoxymethyl)-2,6-dimethoxyphenyl]boronic ...",CCOCc1cc(OC)c(B(O)O)c(OC)c1,0
...,...,...,...
278,Diphenylcyclopropenone,O=c1c(-c2ccccc2)c1-c1ccccc1,1
279,"Disperse Violet 1 (1,4-diamino-9,10-anthracene...",Nc1ccc(N)c2c1C(=O)c1ccccc1C2=O,1
280,HC Red 13,Nc1ccc(N(CO)CCO)cc1[N+](=O)[O-],1
281,Propyl gallate,CCCOC(=O)c1cc(O)c(O)c(O)c1,1
282,Squaric acid,O=c1c(O)c(O)c1=O,1

In [66]:

train_df["text"] = train_df.apply(row_to_text, axis=1, split = 'train', dataset = 'Skin Reaction')
val_df["text"] = val_df.apply(row_to_text, axis=1, split = 'val', dataset = 'Skin Reaction')
test_df["text"] = test_df.apply(row_to_text, axis=1, split = 'test', dataset = 'Skin Reaction')
print(train_df["text"][0])
# Save the train and test dataframes to csv
train_df = train_df[["text"]]
val_df = val_df[["text", "Y"]]
test_df = test_df[["text", "Y"]]
# create AMES directory if it doesn't exist
os.makedirs('./../data/TDC/Skin', exist_ok=True)
train_df.to_csv('./../data/TDC/Skin/train_df.csv', index=False)
val_df.to_csv('./../data/TDC/Skin/val_df.csv', index=False)
test_df.to_csv('./../data/TDC/Skin/test_df.csv', index=False)

Q: This is the SMILES string of the drug: CCCOc1ccc(Br)c(C(=O)c2ccc(OC)cc2O)c1. Can this drug cause skin reaction?
A: No